/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "CustomKnob.h"
#include "ImageAnimator.h"

#include "GUIUtilities/CustomButton.h"

//==============================================================================
/**
*/
class KissOfShameAudioProcessorEditor  : public AudioProcessorEditor,
                                         public Timer,
                                         public SliderListener,
                                         public Button::Listener
{
public:
    KissOfShameAudioProcessorEditor (KissOfShameAudioProcessor* ownerFilter);
    ~KissOfShameAudioProcessorEditor();
    
    void timerCallback() override;
    
    void sliderValueChanged (Slider*) override;
    
    void buttonClicked (Button* b);
    virtual void timerCallback(int timerID){};
    void changeListenerCallback (ChangeBroadcaster *source){};
    
    
    ScopedPointer<CustomKnob> inputSaturationKnob;
    ScopedPointer<CustomKnob> shameKnob;
    ScopedPointer<CustomKnob> hissKnob;
    ScopedPointer<CustomKnob> blendKnob;
    
    ScopedPointer<CustomButton> bypassButton;
    
    ScopedPointer<ImageAnimator> testAnimation;
    
    
    
        
private:
    
    Image faceImage;
    
    KissOfShameAudioProcessor* getProcessor() const
    {
        return static_cast <KissOfShameAudioProcessor*> (getAudioProcessor());
    }
    
    


    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // PLUGINEDITOR_H_INCLUDED
